version: "3"
services:
    web:
      env_file: ".env"
      build:
        context: .
        target: development
      ports:
      - ${WEB_PORT}:80
      networks:
      - leednetwork
      depends_on :
      - bdd

      

    bdd:
      image: mysql:latest
      env_file: ".env"
      volumes:
      - ./bdd-volume:/var/lib/mysql
      networks:
      - leednetwork
      ports : 
      - ${BDD_PORT}:3306
networks:
  leednetwork:
    name: leednetwork